# Generated by Django 4.2.4 on 2023-08-23 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('municipal', models.CharField(max_length=50)),
                ('year_estd', models.CharField(max_length=4)),
                ('type', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=7)),
                ('emis_code', models.CharField(max_length=50)),
                ('head_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('tel_no', models.CharField(max_length=10)),
                ('digital_add', models.CharField(max_length=13)),
                ('location', models.CharField(max_length=20)),
                ('sch_no', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=10)),
                ('othernames', models.CharField(blank=True, max_length=40)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('staff_ID', models.CharField(max_length=7)),
                ('NTC_no', models.CharField(max_length=15)),
                ('regd_no', models.CharField(max_length=7)),
                ('SSNIT_no', models.CharField(max_length=15)),
                ('present_rank', models.CharField(max_length=40)),
                ('date_promoted_to_rank', models.DateField()),
                ('contact_no', models.CharField(max_length=10)),
                ('residence', models.CharField(max_length=40)),
                ('salary_level', models.CharField(max_length=10)),
                ('periods_per_week', models.IntegerField()),
                ('previous_station', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=7)),
                ('date_of_first_appointment', models.DateField()),
                ('date_posted_to_present_station', models.DateField()),
                ('subjects_teaching', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=40)),
                ('account_no', models.CharField(max_length=20)),
                ('academic_qualification', models.CharField(max_length=60)),
                ('date_of_academic_qualification', models.DateField()),
                ('prof_qualification', models.CharField(max_length=60)),
                ('date_of_prof_qualification', models.DateField()),
                ('duties_assigned', models.CharField(max_length=60)),
                ('profile_image', models.ImageField(upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
