# Generated by Django 4.2.4 on 2023-08-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('municipal', models.CharField(max_length=50)),
                ('year_estd', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=7)),
                ('emis_code', models.PositiveIntegerField()),
                ('head_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('tel_no', models.PositiveIntegerField()),
                ('digital_add', models.CharField(max_length=13)),
                ('location', models.CharField(max_length=20)),
                ('sch_no', models.PositiveIntegerField()),
            ],
        ),
    ]
