# Generated by Django 4.2.4 on 2023-08-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schMgt_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='emis_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='sch_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='tel_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='year_estd',
            field=models.IntegerField(),
        ),
    ]
