# Generated by Django 4.2.4 on 2023-09-28 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schMgt_App', '0002_alter_teacherrecord_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRecordAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=10)),
                ('othernames', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('staff_ID', models.CharField(max_length=7)),
                ('NTC_no', models.CharField(max_length=15)),
                ('regd_no', models.CharField(max_length=7)),
                ('SSNIT_no', models.CharField(max_length=15)),
                ('present_rank', models.CharField(max_length=40)),
                ('date_promoted_to_rank', models.DateField()),
                ('contact_no', models.CharField(max_length=10)),
                ('residence', models.CharField(max_length=40)),
                ('salary_level', models.CharField(max_length=10)),
                ('periods_per_week', models.IntegerField()),
                ('previous_station', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=7)),
                ('date_of_first_appointment', models.DateField()),
                ('date_posted_to_present_station', models.DateField()),
                ('subjects_teaching', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=40)),
                ('account_no', models.CharField(max_length=20)),
                ('academic_qualification', models.CharField(max_length=60)),
                ('date_of_academic_qualification', models.DateField()),
                ('prof_qualification', models.CharField(max_length=60)),
                ('date_of_prof_qualification', models.DateField()),
                ('duties_assigned', models.CharField(max_length=60)),
                ('profile_image', models.ImageField(upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
