# Generated by Django 4.2.4 on 2023-08-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schMgt_App', '0002_alter_school_emis_code_alter_school_sch_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='sch_no',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='school',
            name='tel_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='year_estd',
            field=models.CharField(max_length=4),
        ),
    ]
