# Generated by Django 4.2.4 on 2023-09-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schMgt_App', '0003_teacherrecordadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherrecord',
            name='relationship_status',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='teacherrecordadmin',
            name='relationship_status',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherrecord',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=7),
        ),
        migrations.AlterField(
            model_name='teacherrecordadmin',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=7),
        ),
    ]
