# Generated by Django 4.2.4 on 2023-09-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schMgt_App', '0004_teacherrecord_relationship_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherrecord',
            name='form_teacher',
            field=models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B'), ('NONE YET', 'NONE YET')], default='NONE YET', max_length=10),
        ),
        migrations.AddField(
            model_name='teacherrecordadmin',
            name='form_teacher',
            field=models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B'), ('NONE YET', 'NONE YET')], default='NONE YET', max_length=10),
        ),
    ]
